### ISSUE TITLE
Use a meaningful title on the gist

### ISSUE THREAD

**Issue by Sfshaza** [kasperpeulen/dartpads#1]
I've been playing with the tool and, overall, it looks great!

Can you put a more meaningful name on the gist? Currently it looks like the following:

![screen shot 2015-08-05 at 2 43 03 pm](https://cloud.githubusercontent.com/assets/6293442/9098707/568807fe-3b80-11e5-92ae-7dbf8a35f463.png)

It's hard to tell which gist belongs to which example. Could you use the source code directory name as the name of the gist?

**Comment by kasperpeulen** [comment]
okay, I think if you update the executable with:
`pub global activate --source git https://github.com/kasperpeulen/gist-generator`

it should work now. 

I was thinking maybe if the pubspec.yaml file contains a description, maybe use that as the description for the gist ? And falling back on the directory name (or maybe the pubspec name?).

In this way you could use a complete sentence for describing the gist. Maybe that is useful for people trying to explore the gist ? 

Btw, I'm curious if the gists get proberly updated, or that the tool will create new gist, I hope it just updates them.

**Comment by Sfshaza** [comment]
Excellent! Yes, that fixes both the output and the gist title. Sure, using the description from pubspec on the gist would be nice! (Not essential, but nice.)

The gist files were updated in place. It did not create new gists.

Thanks for that fast turnaround!

**Comment by kasperpeulen** [comment]
@Sfshaza Okay, it now uses the description of the pubspec file, falling back on the directory name

**Comment by Sfshaza** [comment]
I really like how it now tells me why it skipped some examples!

But maybe we should go back to the directory name on the gist itself. It now looks like this:

![screen shot 2015-08-05 at 3 29 40 pm](https://cloud.githubusercontent.com/assets/6293442/9099603/e3f2caf6-3b86-11e5-97f1-ad9cce27da17.png)

You can't always count on the description being descriptive enough.

**Comment by kasperpeulen** [comment]
ah I see, reverted

**Comment by Sfshaza** [comment]
Thx!
