### ISSUE TITLE
More meaningful output at the command line

### ISSUE THREAD

**Issue by Sfshaza** [kasperpeulen/dartpads#2]
When I run the gist generator from the command line, the output looks like this:

![screen shot 2015-08-05 at 2 46 28 pm](https://cloud.githubusercontent.com/assets/6293442/9098799/db5b44aa-3b80-11e5-9bc4-898fb8b4f7cc.png)

Could you change the output to indicate which example is associated with which gist? So it might look like the following:

"portmanteaux" gist updated at https://gist.github.com/43e6160a9cde397e1907
"mini" gist updated at https://gist.github.com/87b31cee5b57c3678429
"mini_with_style" gist updated at https://gist.github.com/e1ad038d9bea1902c48e

**Comment by kasperpeulen** [comment]
I think this is also fixed now.
