### ISSUE TITLE
Indicate reason for failure

### ISSUE THREAD

**Issue by Sfshaza** [kasperpeulen/dartpads#3]
Could you indicate why a gist file was not created for a particular example? The output, for example, might look like:

'cmdline' - no "web" directory
'anagram' - no "main.dart" file
'portmanteaux' - updated at https://gist.github.com/43e6160a9cde397e1907
'portmanteaux_simple' - too many files
'mini' -  updated at https://gist.github.com/87b31cee5b57c3678429
'mini_with_style' - updated at https://gist.github.com/e1ad038d9bea1902c48e

**Comment by kasperpeulen** [comment]
seems fixed
